// GENERATED by scripts/build_visemes.py — do not edit by hand.
// Mouth shapes from a single stable head pose, closed -> widest.
export const VISEME_COUNT = 12;
export const VISEME_SRCS: string[] = Array.from(
  { length: 12 },
  (_, i) => `/avatar/viseme-${String(i).padStart(2, '0')}.webp`
);
/** Resting face — also the poster/preload image. */
export const VISEME_IDLE = VISEME_SRCS[0];
// Normalized openness of each frame (0 = closed, 1 = widest).
export const VISEME_OPENNESS: number[] = [0.0, 0.0351, 0.278, 0.2869, 0.3645, 0.4613, 0.5466, 0.6294, 0.6735, 0.7447, 0.8885, 1.0];
