// GENERATED by scripts/build_visemes.py — do not edit by hand.
// Mouth shapes sampled from the memoji video, ordered closed -> widest.
export const VISEME_SHEET = '/avatar-visemes.webp';
export const VISEME_COUNT = 24;
export const VISEME_COLS = 6;
export const VISEME_ROWS = 4;
// Normalized openness actually achieved by each tile (0 = closed).
export const VISEME_OPENNESS: number[] = [0.0, 0.0427, 0.0876, 0.128, 0.1781, 0.2188, 0.2599, 0.2993, 0.3512, 0.3931, 0.4362, 0.4789, 0.525, 0.5676, 0.6071, 0.6588, 0.686, 0.745, 0.7973, 0.8317, 0.8613, 0.9187, 0.9434, 1.0];
