#!/usr/bin/env python3
"""
Build the avatar mouth frames from the source memoji video.

Emits one image per mouth shape rather than a sprite sheet. A sheet needs
background-size/background-position math that has to stay exactly in sync with
the grid, and when it drifts you get two half-faces in one circle. Separate
files swap with `img.src` — there is no geometry to get wrong, and the browser
caches them after the first paint.

Also crops off the pillarbox and the "Veo" watermark in it.

Usage:  python3 scripts/build_visemes.py
Writes: public/avatar/viseme-NN.webp  and  src/components/fun/visemes.ts
"""

import glob
import json
import os
import shutil
import subprocess
import tempfile

from PIL import Image

SRC = "assets/final_memojis.webm"
OUT_DIR = "public/avatar"
TABLE = "src/components/fun/visemes.ts"

FPS = 24
LEVELS = 24          # mouth-openness steps, closed -> widest
TILE = 256           # px per frame
CONTENT = (280, 0, 1000, 720)   # strips pillarbox + watermark


def openness(img: Image.Image) -> float:
    """Fraction of dark pixels in the mouth region — proxy for how open it is."""
    g = img.convert("L")
    w, h = g.size
    mouth = g.crop((int(w * 0.40), int(h * 0.55), int(w * 0.60), int(h * 0.72)))
    px = list(mouth.getdata())
    return sum(1 for p in px if p < 90) / len(px)


def main() -> None:
    tmp = tempfile.mkdtemp()
    try:
        subprocess.run(
            ["ffmpeg", "-v", "error", "-i", SRC, "-vf", f"fps={FPS}",
             os.path.join(tmp, "%04d.png"), "-y"],
            check=True,
        )
        frames = sorted(glob.glob(os.path.join(tmp, "*.png")))
        if not frames:
            raise SystemExit("no frames extracted")

        measured = [(f, openness(Image.open(f).crop(CONTENT))) for f in frames]
        lo = min(o for _, o in measured)
        hi = max(o for _, o in measured)
        print(f"{len(measured)} frames, openness {lo:.4f}..{hi:.4f}")

        # For each evenly spaced openness level, take the closest real frame.
        chosen = []
        for i in range(LEVELS):
            target = i / (LEVELS - 1)
            best = min(
                measured,
                key=lambda fo: abs(((fo[1] - lo) / (hi - lo) if hi > lo else 0) - target),
            )
            chosen.append(best)

        shutil.rmtree(OUT_DIR, ignore_errors=True)
        os.makedirs(OUT_DIR, exist_ok=True)

        total = 0
        for i, (f, _) in enumerate(chosen):
            tile = Image.open(f).crop(CONTENT).resize((TILE, TILE), Image.LANCZOS)
            path = os.path.join(OUT_DIR, f"viseme-{i:02d}.webp")
            tile.save(path, "WEBP", quality=86, method=6)
            total += os.path.getsize(path)

        src_kb = os.path.getsize(SRC) / 1024
        print(f"{LEVELS} frames -> {OUT_DIR}: {total/1024:.0f} KB total "
              f"(source video {src_kb:.0f} KB)")

        with open(TABLE, "w") as fh:
            fh.write(
                "// GENERATED by scripts/build_visemes.py — do not edit by hand.\n"
                "// Mouth shapes sampled from the memoji video, closed -> widest.\n"
                f"export const VISEME_COUNT = {LEVELS};\n"
                "export const VISEME_SRCS: string[] = Array.from(\n"
                f"  {{ length: {LEVELS} }},\n"
                "  (_, i) => `/avatar/viseme-${String(i).padStart(2, '0')}.webp`\n"
                ");\n"
                "/** Resting face — also the poster/preload image. */\n"
                "export const VISEME_IDLE = VISEME_SRCS[0];\n"
                "// Normalized openness actually achieved by each frame (0 = closed).\n"
                "export const VISEME_OPENNESS: number[] = "
                + json.dumps([round(((o - lo) / (hi - lo)) if hi > lo else 0, 4)
                              for _, o in chosen])
                + ";\n"
            )
        print(f"{TABLE} written")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    main()
