#!/usr/bin/env python3
"""
Build the avatar viseme sprite sheet from the source memoji video.

Why a sprite sheet instead of scrubbing the video:
the source webm has only 2 keyframes across 192 frames, so seeking to an
arbitrary timestamp costs up to ~128 frames of decode. That is unusable for
per-frame, amplitude-driven mouth movement. Baking the distinct mouth shapes
into one image makes switching a background-position change — instant, and it
works on Safari/iOS where the webm never played at all.

Also crops off the pillarbox and the "Veo" watermark that sits in it.

Usage:  python3 scripts/build_visemes.py
Writes: public/avatar-visemes.webp  and  src/components/fun/visemes.ts
"""

import glob
import json
import os
import shutil
import subprocess
import tempfile

from PIL import Image

SRC = "assets/final_memojis.webm"
SHEET = "public/avatar-visemes.webp"
TABLE = "src/components/fun/visemes.ts"

FPS = 24
LEVELS = 24          # mouth-openness steps, closed -> widest
TILE = 320           # px per frame in the sheet
COLS = 6
CONTENT = (280, 0, 1000, 720)   # strips pillarbox + watermark


def openness(img: Image.Image) -> float:
    """Fraction of dark pixels in the mouth region — proxy for how open it is."""
    g = img.convert("L")
    w, h = g.size
    mouth = g.crop((int(w * 0.40), int(h * 0.55), int(w * 0.60), int(h * 0.72)))
    px = list(mouth.getdata())
    return sum(1 for p in px if p < 90) / len(px)


def main() -> None:
    tmp = tempfile.mkdtemp()
    try:
        subprocess.run(
            ["ffmpeg", "-v", "error", "-i", SRC, "-vf", f"fps={FPS}",
             os.path.join(tmp, "%04d.png"), "-y"],
            check=True,
        )
        frames = sorted(glob.glob(os.path.join(tmp, "*.png")))
        if not frames:
            raise SystemExit("no frames extracted")

        measured = []
        for f in frames:
            im = Image.open(f).crop(CONTENT)
            measured.append((f, openness(im)))

        lo = min(o for _, o in measured)
        hi = max(o for _, o in measured)
        print(f"{len(measured)} frames, openness {lo:.4f}..{hi:.4f}")

        # For each evenly spaced openness level, take the closest real frame.
        chosen = []
        for i in range(LEVELS):
            target = i / (LEVELS - 1)
            best = min(
                measured,
                key=lambda fo: abs(((fo[1] - lo) / (hi - lo) if hi > lo else 0) - target),
            )
            chosen.append(best)

        rows = (LEVELS + COLS - 1) // COLS
        sheet = Image.new("RGBA", (COLS * TILE, rows * TILE), (0, 0, 0, 0))
        for i, (f, _) in enumerate(chosen):
            tile = Image.open(f).crop(CONTENT).resize((TILE, TILE), Image.LANCZOS)
            sheet.paste(tile, ((i % COLS) * TILE, (i // COLS) * TILE))

        sheet.save(SHEET, "WEBP", quality=88, method=6)
        size_kb = os.path.getsize(SHEET) / 1024
        src_kb = os.path.getsize(SRC) / 1024
        print(f"{SHEET}: {size_kb:.0f} KB  (source video {src_kb:.0f} KB)")

        with open(TABLE, "w") as fh:
            fh.write(
                "// GENERATED by scripts/build_visemes.py — do not edit by hand.\n"
                "// Mouth shapes sampled from the memoji video, ordered closed -> widest.\n"
                f"export const VISEME_SHEET = '/{os.path.basename(SHEET)}';\n"
                f"export const VISEME_COUNT = {LEVELS};\n"
                f"export const VISEME_COLS = {COLS};\n"
                f"export const VISEME_ROWS = {rows};\n"
                "// Normalized openness actually achieved by each tile (0 = closed).\n"
                "export const VISEME_OPENNESS: number[] = "
                + json.dumps([round(((o - lo) / (hi - lo)) if hi > lo else 0, 4)
                              for _, o in chosen])
                + ";\n"
            )
        print(f"{TABLE} written")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    main()
